### ISSUE TITLE
new Date("..string") example code does not work in all browser (Safari)

### ISSUE THREAD

**Issue by lajpatshah** [JWGmeligMeyling/jqm-calendar#13]
The calendar is not showing any events in safari

**Comment by rsdickerson** [comment]
I'm experiencing this issue. When I view the calendar on a Windows desktop browser (Opera or Chrome) I see the events. When I view the calendar on Macbook Pro Chrome I see the events, but not viewing calendar with Safari. See the same issue when viewing calendar on iPhone using Safari (haven't tested yet with Chrome on iPhone, but expect it will work).

Since you are not able to reproduce, this issue must be caused by something I'm doing. I'll keep working on finding a resolution locally, but sure would appreciate any suggestions on what to look for.

**Comment by JWGmeligMeyling** [comment]
If we have a plunkr or jsfiddle we can test it on different browsers.

**Comment by rsdickerson** [comment]
I'll send plunkr link later today. Work firewall is blocking saving it. Thanks.

**Comment by rsdickerson** [comment]
OK, here's a plunker that for me works fine on Opera and Chrome, but on Safari the events do not appear. I'm using desktop browsers to test this, but am seeing the same issue on iPhone Safari.

http://plnkr.co/edit/47ZXOaX2ZOkndNd1q27f?p=preview

My first time using Plunker, so let me know if I need to do something different.

**Comment by JWGmeligMeyling** [comment]
Confirmed.

**Comment by rsdickerson** [comment]
The problem turns out to be how I was creating the begin and end dates (e.g. new Date("2015-06-16 07:00")) in the events. This SO question (http://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome) led me to the solution. 

I changed to new Date(year,month,day,hour,minute) and now it works fine in Safari, too.

**Comment by rsdickerson** [comment]
You might want to change the demo code to use this constructor instead of the new Date(String date) just so others who follow the demo will not run into this same problem.

Thanks. Awesome product by the way. Really appreciate your efforts.

**Comment by JWGmeligMeyling** [comment]
Yes we should update the example. Luckily this isn't a bug in the calendar :smile: Thanks for your effort to sort this out!

**Comment by luigi37** [comment]
Updated demo example according to rsdickerson comment
