### ISSUE TITLE
Question: What would be involved in upgrading jqm-calendar to JQM 1.4.5?

### ISSUE THREAD

**Issue by rsdickerson** [JWGmeligMeyling/jqm-calendar#35]
Just wondering if you have an upgrade in your roadmap. 

I started an attempt to upgrade jqm-calendar to JQM 1.4.5, but seems the only upgrade guide available for JQM is from 1.3 to 1.4. Ultimately, I just need a Flat UI theme and there are free ones available, but only for JQM 1.4.

My plan now is to create a flat custom JQM theme for 1.2.1 and move on.

**Comment by rsdickerson** [comment]
I got it working with jqm 1.3.2 by making the following change to my code:

$("#view-calendar").live('pageinit', function(event, ui) {

changed to...

$(document).on('pageinit', "#view-calendar", function (event, ui) {

Seems the .live method was removed. 
https://jquery.com/upgrade-guide/1.9/#live-removed

At least that's progress. :)

**Comment by rsdickerson** [comment]
Nevermind about the original question. I found a flat ui theme I can use with JQM 1.3.1, so I'm good.

Thanks.

**Comment by JWGmeligMeyling** [comment]
@rsdickerson  `live` is removed indeed. I think i really need to update the examples someday :wink: 
The problem is I have very little time and very little reason to update the calendar now (as I am not using it myself currently). The calendar does uses very little jQuery calls in the end, only some DOM manipulation and event listening. Patching it to newer versions should be relatively easy.
