### ISSUE TITLE
Last version does not work (at least on Chrome desktop and mobile)

### ISSUE THREAD

**Issue by monkiki** [JWGmeligMeyling/jqm-calendar#39]
Hi,

I've downloaded last version but it does not show the days in the calendar. I can only see an horizontal line.

![image](https://cloud.githubusercontent.com/assets/130590/10042593/5487c1e6-61ec-11e5-8f65-658c21a165f7.png)

**Comment by JWGmeligMeyling** [comment]
Is this since the last version or on the last version?

Verstuurd vanaf mijn iPhone

Op 23 sep. 2015 om 12:11 heeft monkiki <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi,

I've downloaded last version but it does not show the days in the calendar. I can only see an horizontal line.

[image]<https://cloud.githubusercontent.com/assets/130590/10042561/29b915f0-61ec-11e5-9fb2-b1cd86106475.png>

**Comment by monkiki** [comment]
Well, I've downloaded from https://github.com/JWGmeligMeyling/jqm-calendar/archive/master.zip . Is it the last version?

**Comment by JWGmeligMeyling** [comment]
It should be. Does the old version work?
https://github.com/JWGmeligMeyling/jqm-calendar/raw/a6eb713cf0c3eab7b5f10a8d11038a91f07d077c/jw-jqm-cal.js

**Comment by monkiki** [comment]
Same problem. It may be a CSS issue.

**Comment by monkiki** [comment]
Nope, also fails with old CSS. This is the working version: 

https://www.dropbox.com/s/rlokjsfmd1ruvdd/jqcal.zip?dl=0

**Comment by luigi37** [comment]
Hi Monkiki, the issue is linked to the linked jquery and jquerymobile libraries which are old... I'm updating the example html file.
Please confirm if it works. Thanks

**Comment by monkiki** [comment]
Yes, it works. Thanks!

**Comment by luigi37** [comment]
Thank you for having confirmed!
